config/routes.rb
Rails.application.routes.draw do
  root "books#index"
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, :author, :description, presence: true
    validates :rating, numericality: { greater_than: 0, less_than: 11, :only_integer => true  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def show
    @book = Book.find(params[:id])
  end


  private
    def book_params
      params.require(:book).permit(:title, :author, :rating, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
    def star_rating(rating:)
        rating = rating.to_i
        return_string = ""
        (1..rating).each{
            return_string += "★"
        }
        (1..10-rating).each{
            return_string += "☆"
        }
        return return_string
    end
    
end

app/views/books/index.html.erb
<h1>O que achou do livro?</h1>
<p>Blog sobre resenhas de livros</p>
<ul>
  <% @books.each do |book| %>
    <li>
      <%= link_to book.title, book %>
    </li>
  <% end %>
</ul>

<%= link_to "Novo livro", new_book_path %>

app/views/books/new.html.erb
<h1>Leu mais um livro? Bora registrar!</h1>

<%= form_with model: @book do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @book.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :author %><br>
    <%= form.text_area :author %>
        <% @book.errors.full_messages_for(:author).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  
  <div>
    <%= form.label :rating %><br>
    <%= form.text_area :rating %>
        <% @book.errors.full_messages_for(:rating).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
        <% @book.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/show.html.erb
<h1><strong><%= @book.title %></strong></h1>
<p>Escrito por <strong><%= @book.author %></strong></p>
<p>Avalia&ccedil;&atilde;o: <strong><%= star_rating(rating: @book.rating) %></strong></p>
<p>Sobre o livro:</p>
<p><%= @book.description %></p>
<p>&nbsp;</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>